build:
  image: framgia/laravel-workspace
  commands:
    - cp .env.example .env
    - composer install
    - bower install
    - npm install
    - gulp
    - framgia-ci test-connect 127.0.0.1 3306 60
    - framgia-ci run
compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  rocketeer:
    image: fdplugins/rocketeer:php5
    when:
      branch: develop
    commands:
      - rocketeer deploy --on=staging --no-interaction
cache:
  mount:
    - vendor
    - node_modules
    - .git
